services:
  jenkins:
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8880:8080"
    volumes:
      - ./jenkins_controller/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml
      - ./jenkins_controller/jobs:/usr/share/jenkins/ref/jobs
    restart: always
    networks:
      - shared_network
  
  jenkins_agent:
    depends_on:
      - jenkins
    container_name: jenkins_agent
    build: jenkins_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJxXl+C4GsmIcrsXQ+mqS/t9SNsFrtj5LffdnNr8+9a40UUHDX1mKe26U8oSarCciLYEtXWsWtl1VmQS6JAdVI5vZKS2J0Nt6oe+AH9y2PhL6wtqUsel2aJHUk8w13Dfkt+w6tZBQxCuzBDvWRt6hsprVuJvWoICMZanVOoXb+BfJx9133mG/uviF/rgtEqn5CqTbHWN1cUs+jei0GOlfyQr/GR7P5cP6baxe5yxCebohlgbYvDrwUT2ZBSlJHIaqbrbeBF/yigCcWCA9z46PubKc/qIcDY5qeFuldy0mqEdpMILDLjcrtidnp4wvRa8cxZl4w9fNYGwK8C56/b9n
    restart: always
    networks:
      - shared_network
  
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    ports:
      - '8929:80'
      - '2224:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'pandapanda'
        #        external_url 'http://192.168.44.44:8929'
    networks:
      - shared_network
  
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './gitlab-runner:/etc/gitlab-runner'
    restart: always
    networks:
      - shared_network
    depends_on:
      - gitlab

networks:
  shared_network:
    name: shared_network
